/**
 * Copyright (c) Small Trading Company Ltd (Destash.com).
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 */

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Engineer.Analyzers
{
    [Generator]
    public class EngineerIncrementalSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            GeneratorLogging.SetLoggingLevel(LoggingLevel.Fatal);
            // GeneratorLogging.SetLogFilePath("/Users/tom/GitHub/engineer/src/Engineer.Analyzers/EngineerIncrementalSourceGeneratorLog.txt");
            try
            {
                context.RegisterPostInitializationOutput(static postInitializationContext =>
                {
                    // postInitializationContext.AddEmbeddedAttributeDefinition();
                    postInitializationContext.AddSource("EngineerAttributes.g.cs", SourceText.From("""
                // <auto-generated/>

                #nullable enable annotations
                #nullable disable warnings

                // Suppress warnings
                #pragma warning disable CS0612, CS0618, CS9113, CS1591

                using System;
                using Microsoft.CodeAnalysis;

                namespace Engineer
                {
                    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
                    internal sealed class EngineerCodeAttribute : Attribute
                    {
                    }
                }
                """, Encoding.UTF8));
                });

                var compilationProvider = context.CompilationProvider;

                var graphNodeProvider = context
                    .SyntaxProvider
                    .ForAttributeWithMetadataName(
                        "Engineer.EngineerCodeAttribute",
                        predicate: static (node, cancelToken) => HasEngineerAttribute(node),
                        transform: static (ctx, cancelToken) => GetTransform(ctx));

                var combined = graphNodeProvider.Combine(compilationProvider);

                context.RegisterSourceOutput(
                    combined,
                    (sourceProductionContext, source) => Generate(source.Left, source.Right, sourceProductionContext));
            }
            catch (Exception ex)
            {
                GeneratorLogging.LogMessage(ex.ToString(), LoggingLevel.Error);
                throw;
            }
        }

        private static void Generate(EngineerTransform transform, Compilation compilation, SourceProductionContext context)
        {
            try
            {

            }
            catch (Exception ex)
            {
                GeneratorLogging.LogMessage(ex.ToString(), LoggingLevel.Error);
                throw;
            }
        }

        private static bool HasEngineerAttribute(SyntaxNode node)
        {
            try
            {
                GeneratorLogging.LogMessage($"HasEngineerAttribute");
                return node is ClassDeclarationSyntax classDeclaration && classDeclaration
                    .AttributeLists
                    .SelectMany(a => a.Attributes)
                    .Where(IsEngineerAttribute)
                    .Any();
            }
            catch (Exception ex)
            {
                GeneratorLogging.LogMessage(ex.ToString(), LoggingLevel.Error);
                throw;
            }
        }

        private static bool IsEngineerAttribute(AttributeSyntax attribute)
        {
            GeneratorLogging.LogMessage($"IsEngineerAttribute");
            var name = attribute.Name.GetText().ToString();
            return name == "EngineerCode" || name == "EngineerAttribute";
        }

        private static bool IsEngineerAttribute(AttributeData attribute)
        {
            GeneratorLogging.LogMessage($"IsEngineerAttribute");
            return attribute.AttributeClass?.Name == "EngineerCodeAttribute";
        }

        private static EngineerTransform GetTransform(GeneratorAttributeSyntaxContext ctx)
        {
            try
            {
                return new EngineerTransform();
            }
            catch (Exception ex)
            {
                GeneratorLogging.LogMessage(ex.ToString(), LoggingLevel.Error);
                throw;
            }
        }
    }

    public sealed record EngineerTransform();

}
